# -*- coding: utf-8 -*-
"""Untitled42.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aFfBqNatURSuKbTbpH4Yp105fGMJxHIV
"""

import pandas as pd

# load the books excel file
books_df = pd.read_excel('books_1.Best_Books_Ever.csv.xlsx')

# get user's favorite genres
user_fav_genres = input('Enter your favorite genres (separated by commas): ').split(',')

# use content-based filtering to filter books based on matching genres
genre_cols = ['genre 1', 'genre 2', 'genre 3', 'genre 4','genre 5']
matched_books_df = books_df[books_df[genre_cols].isin(user_fav_genres).any(axis=1)]
genre_counts = matched_books_df[genre_cols].apply(lambda x: sum(x.isin(user_fav_genres)), axis=1)
matched_books_df = matched_books_df[genre_counts >= 2].reset_index(drop=True)

# use collaborative filtering to filter out books already read and rated highly by the user
user_df = pd.read_csv('goodreads_interactions (1).csv')
user_ratings_df = user_df[user_df['Rating'] >= 4]  # consider only high ratings
user_rated_book_ids = user_ratings_df['book_id'].unique()
collab_filtered_books_df = matched_books_df[~matched_books_df['book_id'].isin(user_rated_book_ids)]

# calculate weighted score for the remaining books
C = books_df['rating'].mean()
m = books_df['numRatings'].quantile(0.9)
collab_filtered_books_df['weighted_score'] = (collab_filtered_books_df['numRatings'] / (collab_filtered_books_df['numRatings'] + m) * collab_filtered_books_df['rating']) + (m / (collab_filtered_books_df['numRatings'] + m) * C)

# sort the books by weighted score and display top 10 recommendations
collab_filtered_books_df = collab_filtered_books_df.sort_values('weighted_score', ascending=False).reset_index(drop=True)
print(f"Recommended books for {', '.join(user_fav_genres)}:\n")
for i, book in collab_filtered_books_df.head(10).iterrows():
    print(f"{i+1}. {book['book_id']} ({book['title']}) - {book['weighted_score']:.2f} weighted score, {book['likedPercent']}% liked")