# -*- coding: utf-8 -*-
"""Untitled42.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aFfBqNatURSuKbTbpH4Yp105fGMJxHIV
"""

import pandas as pd

# Load the book data and ratings data into separate dataframes
book_data = pd.read_excel('books_1.Best_Books_Ever.csv.xlsx')
ratings_data = pd.read_csv('goodreads_interactions (1).csv')

# Merge the two dataframes on the ISBN column to combine book information and ratings information
book_ratings = pd.merge(book_data, ratings_data, on='book_id')

# Group the data by ISBN and compute the average rating and number of ratings for each book
grouped_data = book_ratings.groupby(['book_id']).agg({'rating': 'mean', 'numRatings': 'count'})

# Create a popularity score for each book based on the average rating and number of ratings
grouped_data['popularity_score'] = (grouped_data['rating'] * grouped_data['numRatings']) / (grouped_data['numRatings'] + 10)

# Sort the data by popularity score in descending order and print the top 10 books
grouped_data.sort_values(by=['popularity_score'], ascending=False, inplace=True)
print(grouped_data.head(10))